# pull official base image
FROM python:3.8-alpine

# set work directory
WORKDIR /usr/src/proj

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
COPY ./requirements.txt .
RUN apk --no-cache -U upgrade && \
    apk --no-cache add postgresql-dev gcc python3-dev musl-dev && \
    sync && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

# copy project
COPY . .

# Run the project
ENTRYPOINT ["/usr/src/proj/run.sh"]
